documenting StructTactics.v (fixes #14)
uwplse/StructTact pull request #49
Opened 2017-03-30 20:25 UTC by Ptival

Note: I didn't bother understanding `insterU` and `find_insterU`. If you have a suggestion for documenting these, let me know.

2017-03-30 20:44 UTC, dwoos requested changes
Looks good modulo the requested changes. Thanks for doing this!!

2017-03-30 20:44 UTC, dwoos commented on StructTactics.v
> +(** [break_inner_match_goal] tries to destruct the innermost [match] it
should be `break_inner_match_hyp`

2017-03-30 20:44 UTC, dwoos commented on StructTactics.v
> +(** [break_inner_match_goal] tries to destruct the innermost [match] it
should be `break_inner_match`

2017-03-30 20:44 UTC, dwoos commented on StructTactics.v
> +(** [find_higher_order_rewrite] tries to [rewrite <-] with
should be `find_reverse_higher_order_rewrite`

2017-03-30 20:44 UTC, dwoos commented on StructTactics.v
> +(** [find_apply_lem_hyp lem] finds a hypothesis where [lem] can be
should be `find_eapply_lem_hyp`

2017-03-30 20:44 UTC, dwoos commented on StructTactics.v
> +(** [find_false] tries to solve the goal by contradiction, using some hypothesis. *)
Not quite--it applies the hypothesis it finds of the form `<x> -> False`, but doesn't subsequently try to solve the goal. So it turns the goal into the premise of the hypothesis of the form `<x> -> False`.

2017-04-01 03:35 UTC, Ptival commented
Review addressed.

2017-04-02 02:45 UTC, palmskog commented
Am I the only one who thinks the tactic documentation should go in `README.md` too? I mean, how many people really read coqdoc comments?

2017-04-26 17:44 UTC, merged